project:
  name: Spark Medallion Architecture

paths:
  raw: "/Volumes/spark_demo/retail/raw/bigmart_sales.csv"

  bronze: "/Volumes/spark_demo/retail/bronze/bigmart"

  silver: "/Volumes/spark_demo/retail/silver/bigmart"

  gold: "/Volumes/spark_demo/retail/gold/bigmart"

write_mode: overwrite